### ISSUE TITLE
eQTL output

### ISSUE THREAD

**Issue by daniaki** [populationgenomics/exome-results-browsers#58]
### Table
The table should contain the following columns:
- [ ] **id** (string in the form `chrom:bp:a1:a2:gene:cell_type_id:round`)
- [ ] **cell_type_id** (string)
- [ ] **snpid** (string in the form `chrom:bp_a2`
- [ ] **gene_symbol** (string representing the HGNC gene symbol)
- [ ] **gene_id** (string representing the Ensembl gene id)
- [ ] **chrom** (string)
- [ ] **bp** (integer)
- [ ] **global_bp** (integer)
- [ ] **a1** (string ref allele)
- [ ] **a2** (string alt allele)
- [ ] **p_value** (float)
- [ ] **fdr** (float representing the adjusted p-value)
- [ ] **spearmans_rho** (float representing spearmans rho correlation)
- [ ] **round** (integer conditioning round)

With optional fields (to be clarified):
- [ ] **a2_freq_onek1k**
- [ ] **a2_freq_hrc**
- [ ] **s_statistic**

Removed:
- [x] **q_value**
- [x] **rsquare**
- [x] **genotyped** (string that can have the values `imputed` or `genotyped`)
- [x] **rsid**
- [x] **is_esnp** (boolean indicating if an eQTL is also an eSNP)

### Output
The output should be saved as a single `parquet` file, for example `eqtl.parqet`, partitioned by `global_bp`. If that is not possible due to compute limitations, then rows should be grouped by chromosome and saved to a single gzipped `tsv` file in a folder named `eqtl`. For example, `eqtl/chromosome_1.tsv.gz`, `eqtl/chromosome_2.tsv.gz`...

**Comment by KatalinaBobowik** [comment]
Happy to finish off this one! Just some input on the columns- I had a chat with Anne and Seyhan about eQTL vs eSNP and it seems like eSNPs are just filtered at an FDR of 0.05, so I don't think we need this column. 

The optional fields `rsquare` and `genotyped` are also unnecessary, as they're both only applicable to snp-chip data. `q_value` also isn't necessary since we have FDR. I'll also leave out `rsid` since this seems to be problematic? Although let me know if that changes

**Comment by daniaki** [comment]
Sounds great! I've marked those fields under "removed" and we can modify these columns over time as needed.

**Comment by daniaki** [comment]
[See also](https://github.com/populationgenomics/tob-wgs/issues/97)

**Comment by daniaki** [comment]
Replaced by [tob-wgs issue](https://github.com/populationgenomics/tob-wgs/issues/111)
